apiVersion: v1
kind: Service
metadata:
  name: rightmove-scraper
  labels:
    app: rightmove-scraper
spec:
  selector:
    app: rightmove-scraper
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP